## Head [/head]

### Head list [GET]

+ Response 200 (application/json)

    + Attributes(array[Head])

## Head Details [/head/{id}]

+ Parameters
    + id (required, number, `1`) - Head ID

### Head detail [GET]

+ Response 200 (application/json)

    + Attributes(Head)
