## CelebPager (object)
+ Include Pager
+ data: Celeb, Celeb (array[Celeb], required)

## Celeb (object)
+ id: 7 (number, required)
+ name: `celeb name` (string, required)
+ image_url: `http:\/\/toptalq.hu\/public\/upload\/image.jpg` (string, required)
+ gender: `man` (enum[string], required)
    + Members
        + man
        + woman
+ birth_place: `birth place` (string, required)
+ birth_date: `1900-01-01` (string, required)
+ death_date: `2000-01-01` (string, optional)
+ description: `celeb description` (string, optional)
+ facebook_url: `facebook url` (string, optional)
+ twitter_url: `twitter url` (string, optional)
+ instagram_url: `instagram url` (string, optional)
