## MixedcontentPager (object)
+ Include Pager
+ data: Mixedcontent, Mixedcontent (array[Mixedcontent], required)

## Mixedcontent (object)
+ topic (TopicRelatedArticles, optional)
    + Include TopicRelatedArticles
+ article (Article, optional)
    + Include Article
