## MixedcontentPager (object)
+ Include Pager
+ data: Mixedcontent, Mixedcontent (array[Mixedcontent], required)

## Mixedcontent (object)
+ topic (Topic, optional)
    + Include Topic
+ article (Article, optional)
    + Include Article
