## TopicPager (object)
+ Include Pager
+ data: Topic, Topic (array[Topic], required)

## Topic (object)
+ id: 7 (number, required)
+ title: `topic title` (string, required)
+ image_url: `https:\\toptalq.hu\public\upload\image.jpg` (string, optional)
+ description: `topic description` (string, optional)
+ extended_description: `topic extended description` (string, optional)
+ number_of_articles: 1530 (number, required)
+ number_of_new_articles: 12 (number, optional)
+ number_of_reads: 55437 (number, required)
+ related_articles: Article, Article, Article (array[Article], optional)
+ timeline (optional)
    + Include Timeline
+ current_user (optional)
    + Include UserMetadata

## Timeline (object)
+ left: `left name` (string, required)
+ right: `right name` (string, required)
