## Head article [/head/{head_id}/article?{page,order_by}]

+ Parameters
    + head_id (required, number, `1`) - Head ID
    + page (optional, number) - Oldalszám
    + order_by (optional, enum[string]) - Rendezési mód
        + Members
            + date
            + popularity

### List head's article [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes(ArticlePager)
