## Head highlights [/head/{head_id}/highlight]

+ Parameters
    + head_id (required, number, `1`) - Head ID

### List head's highlights [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes(array[Topic])
