## Mixedcontent [/head/{head_id}/mixedcontent?{page,order_by}]

+ Parameters
    + head_id (required, number, `1`) - Head ID
    + page (optional, number) - Oldalszám
    + order_by (optional, enum[string]) - Rendezési mód
        + Members
            + date
            + popularity

### List head's mixedcontent [GET]

A Mixedcontent object egy wrapper object, aminek csak annyi a szerepe, hogy vegyes listát kaphasson vissza a kliens a TopicRelatedArticles és az Article object-ekből.
Tehát a Mixedcontent object-ben vagy csak "topic" kulcs létezik, és abban a TopicRelatedArticles object, vagy csak az "article" kulcs, és abban az Article object.

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes(MixedcontentPager)
