## Head topic [/head/{head_id}/topic?{page}]

+ Parameters
    + head_id (required, number, `1`) - Head ID
    + page (optional, number) - Oldalszám

### List head's topic [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes(TopicRelatedArticles)
